In [174]:
import numpy as np

# Write a program to create a 5 dimensional array with all zeros and ones


In [77]:
zeros=np.array([0,0,0,0],ndmin=5)

        

In [78]:
print(zeros)

[[[[[0 0 0 0]]]]]


In [79]:
ones=np.array([1,1,1,1],ndmin=5)

In [82]:
print(ones)

[[[[[1 1 1 1]]]]]


# # Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)

In [96]:
x=np.arange(1,31).reshape(3,10)

In [97]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [92]:
x[0,:]=0

In [93]:
x[1,:]=1

In [94]:
x[2,:]=5

In [98]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

# Write a program to create a 3x4 matrix filled with values from 10 to 21.


In [100]:
np.linspace(10,21,12).reshape(3,4)

array([[10., 11., 12., 13.],
       [14., 15., 16., 17.],
       [18., 19., 20., 21.]])

# # Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,


In [40]:
np.diag([0,1,2,3,4,5,6,7,8,9])

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

# Write a program to reverse an array (the first element becomes the last).
#Given array:
#[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]


In [44]:
x=np.arange(12,28)

In [46]:
x[::-1]

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

# #Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100


In [103]:
x=np.arange(1,101).reshape(10,10)

In [104]:
x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [105]:
y=(x>30) &(x<80)&(x%5==0)

In [106]:
x[y]

array([35, 40, 45, 50, 55, 60, 65, 70, 75])

# Write a program to create a 2D array with 1 on the border and 0 inside.


In [144]:
one=np.ones((4,3),dtype=int)

In [145]:
one

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [147]:
one[1:3,1]=0

In [148]:
one

array([[1, 1, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 1, 1]])

# Write a program to create a checkerboard pattern .Don't use default array function
#Checkerboard pattern:                                                   
[[0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0] 


In [10]:
x=np.zeros((8,8),dtype=int)

In [11]:
x

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
x[1::2,::2]=1

In [13]:
x

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [14]:
x[::2,1::2]=1

In [15]:
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# Write a program to find common values between two arrays.
#Expected Output:
#array1: [10 20 40 60]
#array2: [10, 30, 40,50]


In [156]:
a1=np.array([10,220,40,60])
a2=np.array([10,30,40,50])

In [157]:
np.intersect1d(a1,a2)

array([10, 40])

# #Write a program to create an array 2d array and then reshape into 1d array


In [158]:
arraay=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [160]:
arraay

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [161]:
arraay.ndim

2

In [164]:
oned=arraay.reshape(9,)

In [165]:
oned.ndim

1

# Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.


In [166]:
arr=np.arange(1,17).reshape(4,4)

In [167]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# Solve the below problem by using only numpy functions on the  below given data set


In [72]:
x=np.genfromtxt(r"C:\Users\Dell\Downloads\train_extended.csv",delimiter=',',skip_header=1)

In [73]:
x

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

# what is the max &min length

In [202]:
max=np.max(x,axis=0)

In [203]:
max_length=max[0]

In [204]:
max_length

7.58349125

In [215]:
min=np.min(x,axis=0)

In [216]:
min

array([0.        , 0.        , 0.        , 0.0283495 , 0.01417475,
       0.01417475, 0.04252425, 1.        ])

In [211]:
min_length=min[0]

In [212]:
min_length

0.0

# differences between max &min length

In [213]:
difference=max_length-min_length

In [214]:
difference

7.58349125

# differences between max &min length

In [24]:
def f(x):
    return np.max(x)-np.min(x)

In [25]:
diff=np.apply_along_axis(f,0,x)

In [26]:
diff

array([ 7.58349125,  2.25      ,  2.825     , 80.07316275, 45.25997675,
       26.1098895 , 36.9960975 , 28.        ])

In [221]:
difference_lenth=diff[0]

In [223]:
difference_lenth

7.58349125

# what is the column-wise average ?

In [43]:
def average(x):
    return sum(x)/len(x)


In [45]:
np.apply_along_axis(average,0,x)

array([ 1.31244808,  1.02032036,  0.34602787, 23.12343631,  9.98937025,
        4.99318096,  6.63422915,  9.950615  ])

# what is the avg height and weight of the person whose age is 10 

In [83]:
height=x[:,2]

In [84]:
weight=x[:,3]

In [85]:
age=x[:,7]

In [57]:
avg_height=np.median(height[age==10])

In [61]:
print('average height whose age is 10 is',avg_height)

average height whose age is 10 is 0.3875


In [60]:
avg_weight=np.median(weight[age==10])

In [63]:
print('average weight whose age is 10 is ',avg_weight)

average weight whose age is 10 is  28.2077525


# what is the avg height of persons whose age in between 14&19 

In [97]:
age

array([10., 19., 11., ...,  7., 11., 11.])

In [91]:
mask=(age>=14)&(age<=18)

In [94]:
ages=age[mask]

In [99]:
avg_height=np.median(height[(age>=14)&(age<=18)])

In [100]:
print('average height of persons whose age in between 14&19 is',avg_height )

average height of persons whose age in between 14&19 is 0.4125


# total shell weight

In [156]:
total_shellwt=np.sum(x,axis=0)

In [157]:
total_shellwt

array([ 262489.61599123,  204064.07143302,   69205.57420999,
       4624687.26259666, 1997874.0496096 ,  998636.19134984,
       1326845.82952127, 1990123.        ])

In [158]:
total_shellwt[6]

1326845.8295212665

# differences between shucked weight and viscera weight

In [165]:
diff_wt1=total_shellwt[4]

In [166]:
diff_wt2=total_shellwt[5]

In [167]:
diff_wt=total_shellwt[4]-total_shellwt[5]

In [168]:
diff_wt

999237.8582597616

# find oout the age whose height is >0.4

In [33]:
filter_age=x[:,7][x[:,2]>0.4]

In [37]:
print('the ages whose height >0.4 is ',filter_age)

the ages whose height >0.4 is  [11. 14. 13. ... 11. 11. 11.]


# #avg weight of shucked weight,viscera-weight,shell weight


In [38]:
wt=x[:,4:7]

In [39]:
total_weight=np.sum(wt,axis=0)

In [40]:
def avg_wt(x):
    return sum(x)/len(x)

In [41]:
np.apply_along_axis(avg_wt,0,total_weight)

array(1441118.69016023)

# how many persons belongs each and every unique age

In [53]:
age1=x[:,7:]

In [54]:
age=np.ravel(age1)

In [55]:
age,repeat=np.unique(age,return_counts=True)

In [56]:
age

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 29.])

In [57]:
repeat

array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
       30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
        1591,  1206,   721,   296,   352,   110,    51,    46,    99,
          57], dtype=int64)

# #Solve the below problem by using only numpy on tip data set


In [48]:
ass1=np.genfromtxt(r"C:\Users\Dell\Downloads\tipsf.csv",delimiter=',',skip_header=1)

In [49]:
ass1

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

# total bill_value

In [76]:
bill=np.sum(ass1,axis=0)

In [77]:
total_billvalue=bill[1]

In [79]:
print('total bill value is ',total_billvalue)

total bill value is  4827.770000000001


# total tip value

In [66]:
bill

array([29646.  ,  4827.77,   731.58,   157.  ,    93.  ,   257.  ,
          68.  ,   627.  ])

In [67]:
total_tip=bill[2]

In [72]:
print('total tip is ',total_tip)

total tip is  731.58


# no.of thursdays,fridays,saturdays,sundays present

In [6]:
days=ass1[:,5:6]

In [7]:
def f(x):
    if x==0:
        return 'thursday'
    elif x==1:
        return 'friday'
    elif x==2:
        return 'saturday'
    else:
        return 'sunday'

In [8]:
day=np.vectorize(f,otypes=[str])

In [9]:
total=day(days).ravel()

In [10]:
total_days,repeated=np.unique(total,return_counts=True)

In [13]:
print( 'no.of fridays are ',repeated[0],'no.of saturdays are ',repeated[1],'no.of sundays are ',repeated[2],'no.of thursdays are ',repeated[3])

no.of fridays are  76 no.of saturdays are  62 no.of sundays are  19 no.of thursdays are  87


# number of smokers are present

In [15]:
smoke=ass1[:,4:5]

In [16]:
x=np.where((smoke==1),'smoker','non-smoker').ravel()

In [17]:
smoker_nonsmoker,values=np.unique(x,return_counts=True)

In [18]:
smoker_nonsmoker

array(['non-smoker', 'smoker'], dtype='<U10')

In [19]:
print('no.of smokers are ',values[1])

no.of smokers are  93


# total max tip and min tip

In [21]:
max=np.max(ass1,axis=0)

In [22]:
print('max tip is',max[2])

max tip is 10.0


In [23]:
min=np.min(ass1,axis=0)

In [24]:
print('min tip is ',min[2])

min tip is  1.0


# Number male smokers and female smokers

In [10]:
smokers=ass1[:,4]

In [15]:
number=np.where((ass1[:,3]==1),'male','female')

In [16]:
numbers=number[smokers==1]

In [18]:
male_smokers,female_smokers=np.unique(numbers,return_counts=True)

In [23]:
print('number of male smokers are ',female_smokers[1])
print('number of female smokers are ',female_smokers[0])

number of male smokers are  60
number of female smokers are  33


# find out the average size

In [27]:
avg_size=np.median(ass1[:,7])

In [28]:
print('the average size is ',avg_size)

the average size is  2.0


# what is the is the averge tip given by male and female

In [32]:
tip=ass1[:,2]

In [35]:
avg_tip=np.median(tip[number=='male'])

In [36]:
print('average tip given by male is ',avg_tip)

average tip given by male is  3.0


In [38]:
avg_tip=np.median(tip[number=='female'])

In [39]:
print('average tip given by female is ',avg_tip)

average tip given by female is  2.75


# how much amount spent by male and female

In [41]:
bill=ass1[:,1]

In [43]:
total_bill=np.sum(bill[number=='male'])

In [44]:
print('total amount spent by males are ',total_bill)

total amount spent by males are  3256.8199999999997


In [45]:
total_bill=np.sum(bill[number=='female'])

In [46]:
print('total amount spent by females are ',total_bill)

total amount spent by females are  1570.9499999999996


# number of males and females present are present dinner and lunch

In [51]:
food=np.where((ass1[:,6]==1),'dinner','lunch')

In [53]:
dinner,lunch=np.unique(number[food=='dinner'],return_counts=True)

In [58]:
print('there are',lunch[1],'males are present for dinner')

there are 33 males are present for dinner


In [59]:
print('there are',lunch[0],'females are present for dinner')

there are 35 females are present for dinner


In [64]:
dinner1,lunch=np.unique(number[food=='lunch'],return_counts=True)

In [65]:
print('there are',lunch[1],'males are present for lunch')

there are 124 males are present for lunch


In [66]:
print('there are',lunch[0],'females are present for lunch')

there are 52 females are present for lunch
